config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  filter :locale
  mount ApiFlashcards::Engine, at: "/api"
  mount SwaggerEngine::Engine, at: "/api/v1/docs"
  root "main#welcome"

  get "/analytics" => redirect("https://192.168.50.103:5601")

  scope module: "home" do
    resources :user_sessions, only: [:new, :create]
    resources :users, only: [:new, :create]
    get "login" => "user_sessions#new", :as => :login

    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback"
    get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  end

  scope module: "dashboard" do
    get "batches/new", to: "batches#new", as: "new_batch"
    post "batches/", to: "batches#create", as: "batches"
    post "pusher/auth"
    resources :user_sessions, only: :destroy
    resources :users, only: :destroy
    post "logout" => "user_sessions#destroy", :as => :logout

    get "/flickr_search/search",
      to: "flickr_search#search",
      as: :search
    resources :cards
    resources :blocks do
      member do
        put "set_as_current"
        put "reset_as_current"
      end
    end

    put "review_card" => "trainer#review_card"
    get "trainer" => "trainer#index"

    get "profile/:id/edit" => "profile#edit", as: :edit_profile
    put "profile/:id" => "profile#update", as: :profile
  end
end

app/models/block.rb
class Block < ActiveRecord::Base
  has_many :cards, dependent: :destroy
  belongs_to :user

  validates :title, presence: { message: "Необходимо заполнить поле." }

  def current?
    id == user.current_block_id
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :require_login
  layout "dashboard"
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_authenticated
    redirect_to login_path, alert: t(:please_log_in)
  end

  def not_found
    flash[:alert] = "Вы обратились к несуществующей записи."
    redirect_to root_path
  end
end

app/controllers/dashboard/batches_controller.rb
module Dashboard
  class BatchesController < Dashboard::BaseController
    def new
    end

    def create
      params[:batch][:user_id] = current_user.id
      AddCardsFromUrlJob.perform_later batch_params
      redirect_to cards_path,
                  notice: "Cards adding task from "\
                  "#{batch_params[:url]} was created"
    end

    private

    def batch_params
      params.require(:batch).permit(:url,
                                    :original_selector,
                                    :translated_selector,
                                    :block_id,
                                    :user_id)
    end
  end
end

app/controllers/dashboard/blocks_controller.rb
class Dashboard::BlocksController < Dashboard::BaseController
  before_action :set_block, only: [:show, :destroy, :edit, :update,
                                   :set_as_current, :reset_as_current]

  def index
    @blocks = current_user.blocks.all.order("title")
  end

  def new
    @block = Block.new
  end

  def edit
  end

  def show
  end

  def create
    @block = current_user.blocks.build(block_params)
    if @block.save
      redirect_to blocks_path
    else
      respond_with @block
    end
  end

  def update
    if @block.update(block_params)
      redirect_to blocks_path
    else
      respond_with @block
    end
  end

  def destroy
    @block.destroy
    respond_with @block
  end

  def set_as_current
    current_user.set_current_block(@block)
    redirect_to blocks_path
  end

  def reset_as_current
    current_user.reset_current_block
    redirect_to blocks_path
  end

  private

  def set_block
    @block = current_user.blocks.find(params[:id])
  end

  def block_params
    params.require(:block).permit(:title)
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < Dashboard::BaseController
  before_action :set_card, only: [:destroy, :edit, :update]

  def index
    @cards = current_user.cards.all.order("review_date")
    ahoy.track("Cards index opened")
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      track_flick_photo unless card_params[:remote_image_url].blank?
      ahoy.track("Card added", method: "individual", result: "success")
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def update
    if @card.update(card_params)
      track_flick_photo unless card_params[:remote_image_url].blank?
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def destroy
    @card.destroy
    ahoy.track("Card deleted")
    respond_with @card
  end

  private

  def track_flick_photo
    ahoy.track("Add Flickr photo")
  end

  def set_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date,
                                 :image, :image_cache, :remove_image,
                                 :remote_image_url, :block_id)
  end
end

app/controllers/dashboard/flickr_search_controller.rb
module Dashboard
  class FlickrSearchController < Dashboard::BaseController
    respond_to :js

    def search
      @search_term = params[:search]
      list = if @search_term.blank?
               Flickr.photos.get_recent(per_page: 10)
             else
               ahoy.track("Search Flickr", search: @search_term)
               Rails.cache.fetch("flickr_search_#{@search_term}",
                                 expires_in: 6.hours) do
                 Flickr.photos.search(text: @search_term, per_page: 10)
               end
             end
      @photos = list.map { |photo| photo.square!(150).source_url }
    end
  end
end

app/controllers/dashboard/profile_controller.rb
class Dashboard::ProfileController < Dashboard::BaseController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_profile_path,
                  notice: t(:user_profile_changed)
    else
      respond_with current_user
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :locale)
  end
end

app/controllers/dashboard/pusher_controller.rb
module Dashboard
  class PusherController < Dashboard::BaseController
    protect_from_forgery except: :auth
    def auth
      if current_user
        response = Pusher[params[:channel_name]].
                   authenticate(params[:socket_id])
        render json: response
      else
        render text: "Not authorized", status: "403"
      end
    end
  end
end

app/controllers/dashboard/trainer_controller.rb
class Dashboard::TrainerController < Dashboard::BaseController

  def index
    if params[:id]
      @card = current_user.cards.find(params[:id])
    else
      @card = current_user.cards_for_review.first
    end
  end

  def review_card
    @card = current_user.cards.find(params[:card_id])
    check_result = @card.check_translation(trainer_params[:user_translation])
    if check_result[:state]
      prepare_flash_message(check_result[:distance])
      redirect_to trainer_path
    else
      ahoy.track("Card reviewed", result: "Failure")
      flash[:alert] = t(:incorrect_translation_alert)
      redirect_to trainer_path(id: @card.id)
    end
  end

  private

  def trainer_params
    params.permit(:user_translation)
  end

  def prepare_flash_message(distance)
    if distance == 0
      ahoy.track("Card reviewed", result: "Success")
      flash[:notice] = t(:correct_translation_notice)
    else
      ahoy.track("Card reviewed", result: "Typo/Missprint")
      flash[:alert] = t "translation_from_misprint_alert",
                        user_translation: trainer_params[:user_translation],
                        original_text: @card.original_text,
                        translated_text: @card.translated_text
    end
  end
end

app/controllers/dashboard/user_sessions_controller.rb
class Dashboard::UserSessionsController < Dashboard::BaseController
  def destroy
    logout
    redirect_to login_path, notice: t(:log_out_is_successful_notice)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  def destroy
    current_user.destroy
    redirect_to login_path, notice: "Пользователь успешно удален."
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/dashboard/blocks/_form.html.erb
<%= simple_form_for block do |f| %>
  <div class="form-group">
    <%= f.input :title, label: 'Название',
                input_html: { class: 'form-control', required: true,
                              autofocus: true } %>
  </div>

  <%= f.button :submit, 'Сохранить', class: 'btn btn-default' %>
<% end %>

app/views/dashboard/blocks/edit.html.erb
<h2>Редактировать колоду</h2>

<%= render 'form', block: @block %>

app/views/dashboard/blocks/index.html.erb
<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th>Название</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @blocks.each do |block| %>
    <tr class="table table-hover table-condensed">
      <td><%= block.title %></td>

      <% if block.current? %>
        <td>
          <%= link_to 'Сделать обычной', reset_as_current_block_path(block),
                      method: :put %>
        </td>
      <% else %>
        <td>
          <%= link_to 'Сделать текущей', set_as_current_block_path(block),
                      method: :put %>
        </td>
      <% end %>
      <td><%= link_to 'Редактировать', edit_block_path(block) %></td>
      <td><%= link_to 'Удалить', block, method: :delete,
                      data: { confirm: 'Удалить колоду?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/dashboard/blocks/new.html.erb
<h2>Добавить колоду</h2>

<%= render 'form', block: @block %>

app/views/dashboard/blocks/show.html.erb
<h2><%= @block.title %> - список карточек:</h2>
<h4></h4>

<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th>Оригинал</th>
    <th>Перевод</th>
    <th>Пересмотр</th>
    <th colspan="2"></th>
  </tr>
  </thead>
  <tbody>
  <% @block.cards.each do |card| %>
    <tr class="table table-hover table-condensed">
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.strftime('%d.%m.%Y %H:%M:%S') %></td>
      <td><%= link_to 'Редактировать', edit_card_path(card) %></td>
      <td><%= link_to 'Удалить', card, method: :delete,
                      data: { confirm: 'Удалить запись?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>